### ISSUE TITLE
How you keep tracking of each item?

### ISSUE THREAD

**Issue by karimh777** [ekmungai/eloquent-ifrs#13]
I'm not an Accountant, I want to understand how you can keep tracking of each item in an Invoice or Bill, I've noticed that you only keep a description, amount and quantity and there is no item id.

Also how you perform an update or edit on an Invoice or Bill with Transaction posted to the Ledger, and how partially paid invoices or bills are handled as I understand this effects the transaction and ledger.

**Comment by ekmungai** [comment]
Hi Karim, thanks for your feedback. Each Line Item object has a transaction_id which binds it to a particular transaction. As far as updating already posted transactions is concerened, this throws an exception because it its prohibited by the rules of accounting. Finally, partially paid invoices/bills are kept track of by the Assignment model wherein clearances are recorded. Please let me know if you require any further explanations.

Cheers,
Edward

**Comment by karimh777** [comment]
Thanks, as you know it's hard for non accountants to understand the provided examples. I wish if you can provide a more detailed real world example. Thank you again.

**Comment by ekmungai** [comment]
I see. I'm working on a major release at the moment and will update the documentation as soon as I'm done
