### ISSUE TITLE
can we make a level in this package like

### ISSUE THREAD

**Issue by AAUU-Ansari** [ekmungai/eloquent-ifrs#153]
dear @ekmungai 
I wanted to express my heartfelt thanks for this accounting package. 
Your generosity in sharing your expertise is greatly appreciated. It has been incredibly helpful for my work. 

can we make a level in this package like 
--Transportation Exp.
------Project House One1
----------Mr. xys
-----------------Site1
-----------------Site2

Thanks again!

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari,
Thank you for your kind words. I deliberately chose to stay away from vertical heirarchies because of the problems I encountered with auditing reports from systems that have them. For example, when an expense is posted for Site2, should the double entry go to the Site2, Mr. xys, Project HouseOne1 or Transportation Exp. account? Remember that the double entry rule is scrictly that, double entry. Which means only one account for each side.

Currently, you could achieve basic horizontal leveling using categories, i.e a Site1/Site2 category of (Transportation) Expense Accounts. I'd considered having vertical heirarchies for Categories (as they are not accounts) but I havent had time to consider the reporting implications that would influence the implementation of the feature.

I hope this helps,
Edward
