### ISSUE TITLE
Question about invoice and contact details

### ISSUE THREAD

**Issue by karimh777** [ekmungai/eloquent-ifrs#25]
In the real world example an Invoice has many line items where this invoice also has details as customer name, invoice number, and due date. Items can have categories and min quantity, max quantity and these items referenced in invoice by item_id.

How you suggest to add Invoice details and item details?

Also as you know each customer can have different details (I think it can't be added to accounts table). Do we need a contacts table? and how you suggest we can add contact details?

**Comment by ekmungai** [comment]
Hi karimh. 

Thanks for reaching out. Its true that a real world invoice has many more features than thons described by the package. The idea was to separate completly the accounting from other concerns. The additional details for the invoice (LPO No. Reference etc) can be easily achieved by extending the Invoice model and adding the fields in your own. Similarly, while you could also extend the Accounts model to have contacts fields, this would violate the Single Responsibilty Principle making your application difficult to maintain. A better solution would probably be a seperate Contacts table/model since a single client could have multiple contacts. Even better would be a separate Client model that has relationships to multiple contacts and a single account model. Hope this helps.

Cheers

**Comment by martuico** [comment]
@ekmungai how do I make update on invoice and line since it is connected to ledgers?

**Comment by ekmungai** [comment]
@martuico You can't. By accounting convention once a transacrion has been posted it is immutable. The only way to effect changes to it is to create a reversal transaction (Credit Note for an Invoice) and then make a new Invoice.
