### ISSUE TITLE
Main Account For Journal Entry

### ISSUE THREAD

**Issue by aditiadika** [ekmungai/eloquent-ifrs#47]
hai @ekmungai ,

I have a problem when create journal entry, 
For Journal Entry, what value should i provide for ACCOUNT_ID in ifrs_transactions/main account ?

thanks

**Comment by ekmungai** [comment]
Hi Adit, 

Dealing with the Journal Entry is usually meant for an accountant because they understand the underlying double entry rules. If I were to answer you I would say that the id of any account in the accounts table could fit there, but that wouldn't mean much to you unless you understand accounting.

Hope this helps, cheers

**Comment by aditiadika** [comment]
![Screen Shot 2021-06-14 at 14 14 19](https://user-images.githubusercontent.com/22575137/121853277-efbe4500-cd1a-11eb-8db6-ccea0d4bfc7d.png)

hai @ekmungai, how to input journal entry with multiple debit and multiple credit like shown in the example?

**Comment by ekmungai** [comment]
Hi Dika,

The way the package is structured, all transactions can only have one primary account posted on either side (Dr/Cr) and several line accounts which automatically take up the opposite side of the double entry. This is done deliberately to ensure that the accounts will never be unbalanced on account of a data entry error. In your case in the screenshot, you would need two JE's, one with Cash as the primary account and line items that were paid for in cash, and another for accounts payable and line items that were obtained by credit.

Cheers.

**Comment by aditiadika** [comment]
Thanks for your reply @ekmungai, another question: My Finance team asked how to edit transaction if already posted and we dont want to create adjustment/journal entry. Or is there a way to convert POSTED back to DRAFT ? Please advise.

**Comment by ekmungai** [comment]
Hi @aditiadika,

As the package follows the IFRS rule, which prohibit the adjustment of any transaction that has been commited to the ledger, there is no way of converting as you have asked. The only change is to have strict controls that ensure that transactions are not posted by mistake.

Cheers

**Comment by abanghendri** [comment]
Hi @ekmungai , I saw @aditiadika 's JE screenshot example, it's called compound/combined journal entry

I just wonder how to make compound JE become simpler with your package

Please give me an example to do as @aditiadika 's case

**Comment by ekmungai** [comment]
Hi @abanghendri,

To be honest, given that with a compound JE the double entry integrity would lie in the hands of the user rather than the system, I'd decided against having them in the package altogether. However since you're the second person to ask about them I'm starting to think that perhaps I should extend the package to accomodate them. I'll do some research about their merits and possiby add them in the next release. In the meantime, could you please open an issue specifically to address Compound Journal Entries so we can gauge how important the feature is to the community?

Cheers

**Comment by abanghendri** [comment]
Thanks @ekmungai , I see lot of financial related blogs that say compound journal is very usefull than entry journal for each account

So then, I'll make an issue for it

Again, thanks :)
