### ISSUE TITLE
Overpayment and client statement

### ISSUE THREAD

**Issue by mercrover** [ekmungai/eloquent-ifrs#49]
Thanks @ekmungai for this wonderful package. Am testing out the package but am having challenges with overpayment by client. How can the package be used to allocate client overpayment to a new invoice by the same client and generate client statement?

**Comment by ekmungai** [comment]
Hi Mercrover,

The statement is completely independent from the allocation process since it just displays a chronological list of transactions posted to the account. I think what you mean is the Account Schedule which allocates payments to invoices and only displays those invoices that have not yet been fully paid. 

In this case you have two options, you can directly create an Assignment object with the amount of the overpaymend and the `cleared_id` being the id of the new invoice. Alternatively, You could call `Assignment:: bulkAssign($payment)` to apply the payment to all outstanding invoices on a first come first served basis.

Let me know if this works out for you.

Cheers,
Edward

**Comment by mercrover** [comment]
Hi Edward,

Thanks for clarifying. I'll try both and share any insights.

Cheers!
