### ISSUE TITLE
Issues with Authentication Guard

### ISSUE THREAD

**Issue by hicka** [ekmungai/eloquent-ifrs#54]
Im seeing that the Auth::user() method is used throughout the package to retrieve the logged in user.
This is fine for normal use cases but if this code runs on a Queue or it is used in an Event that is fired by Laravel there is no right way to identify the logged in user. The Queue or Event have no notion of a Session or Auth Guards.

What Im saying is the Queue or any other event that is not directly run under a session should get passed the required data instead to retrieve from the Authenticated user. 

Can we pass the $entity to all required Classes instead of retrieving from Auth::user()->entity ?

**Comment by hicka** [comment]
Are there any plans to refactor the code to enable this? if so I would like to help. @ekmungai

**Comment by ekmungai** [comment]
Hi @hicka,

I actually hadn't even thought about that. I guess the for such cases I'd thought you'd create a special user and log them in using `Auth::loginUsingId($id);`. That being said, the flexibiliy your approach offers would be quite nice to have. Please ma a pull request with your suggested changes, only if you could extend the existing session based system rather than replacing it completely I'd appreciate it. Please also include some test cases that cover then new approach.

Looking forward to seeing the code!

Cheers,
Edward

**Comment by hicka** [comment]
Hi @ekmungai ,
I have the code working and all tests are passing except for one test. That is the TestEntityAuthorizedUser test, it fails because i removed the auth check in Segregating Trait.
I have removed the test for now and it works, if you're okay with that i'd send you a pull request.

About writing new tests, the current tests don't fail because all changes are made to be compatible with the current session based only use. So i guess tests aren't needed for them.
Cheers

**Comment by ekmungai** [comment]
Hi @hicka,

Wow, that was quick. Go ahead and submit the pull request so I can take a look.

Cheers

**Comment by hicka** [comment]
Fixed #71
