### ISSUE TITLE
How to Add Service Charge

### ISSUE THREAD

**Issue by abanghendri** [ekmungai/eloquent-ifrs#90]
Hi @ekmungai , I wonder how to add Service Charge or other fee to the transaction?
because service charge is categorize as Revenue while Vat is Expense?

Thank you

**Comment by ekmungai** [comment]
HI @abanghendri,

I'm afraid you have it wrong, while you are right about Service Charges, Vat is a rather special category in that rather than an expense, it is a cost that is passed on to the consumer of the entity. I hesitate to go into much detail as I am not familiar with the tax rules in your locality and would not want to mislead you. I suggest that you consult an accountant near you for a clearer explanation.

Cheers
