### ISSUE TITLE
Financial Period

### ISSUE THREAD

**Issue by aditiadika** [ekmungai/eloquent-ifrs#96]
hai @ekmungai  ,

How to change the finance reporting period such as November - October?
because when i set year_start in entities table to November and set calendar_year in reporting_periods table to 2021
 i get error "Entity Abc has no reporting period defined for the year 2020".
Please advise on how to change the finance period.

Thanks

**Comment by ekmungai** [comment]
Hi @aditiadika,

When dealing with non-standard (Jan - Dec) you have to be careful about the dates of transactions that you enter. For instance, if you set the year start to November of the current year, it means that no transactions can be entered for any date before Nov 1 2021 since that would mean that they are in the financial year 2020 (1 Nov 2019 - 31 Oct 2021).

Hope this helps.
Edward

**Comment by aditiadika** [comment]
Thanks for advice @ekmungai its worked thanks.
